[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'mkdir -p storage/app/public storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache',
  'chmod -R 775 storage bootstrap/cache',
  'touch database/database.sqlite',
  'chmod 664 database/database.sqlite'
]

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache',
  'php artisan migrate --force',
  'php artisan db:seed --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
